name: Github Actions for LaTeX
description: GitHub Actions to compile LaTeX documents
author: Cheng XU
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for texliveonfly to be invoked
  compiler:
    description: LaTeX engine to be used by texliveonfly
    default: latexmk
  args:
    description: Extra arguments to be passed to texliveonfly
    default: "-pdf -file-line-error -interaction=nonstopmode"
  extra_packages:
    description: Install extra packages by tlmgr
  extra_system_packages:
    description: Install extra packages by apk
runs:
  using: docker
  image: docker/latex-action/Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    - ${{ inputs.extra_packages }}
    - ${{ inputs.extra_system_packages }}
branding:
  icon: book
  color: blue
